import '@onegroup/shared/tokens.css';
import './globals.css';

import type { Metadata, Viewport } from 'next';
import type { ReactNode } from 'react';

import { htmlClassName } from '@onegroup/shared/fonts';

import { JsonLd } from '../components/JsonLd';
import { openGraph, organizationJsonLd, SITE_URL } from '../lib/site';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: 'Precision laser cutting Gateshead | OneLaser',
    template: '%s | OneLaser',
  },
  description:
    '3kW fibre laser cutting in stainless, aluminium and mild steel. Upload a DXF, get a price, and take delivery of parts that fit first time. From the team behind Onesign & Digital.',
  /* Static OG images generated by scripts/generate-og.mjs into
     public/og/ (dark hero frame rebuilt as SVG, rasterised with sharp;
     never a canvas screenshot). */
  openGraph: openGraph('/og/home.png'),
  twitter: { card: 'summary_large_image' },
};

export const viewport: Viewport = {
  themeColor: '#0C1315',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en-GB" className={htmlClassName('onelaser')}>
      <body>
        {children}
        <JsonLd data={organizationJsonLd} />
      </body>
    </html>
  );
}
